// <auto-generated />
using System;
using JWTCommonLibForDotNetCore.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JWTCommonLibForDotNetCore.Migrations
{
    [DbContext(typeof(IdentityContext))]
    partial class IdentityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JWTCommonLibForDotNetCore.Entities.Identity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("Token");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Identities");
                });

            modelBuilder.Entity("JWTCommonLibForDotNetCore.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid?>("IdentityId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("JWTCommonLibForDotNetCore.Entities.Role", b =>
                {
                    b.HasOne("JWTCommonLibForDotNetCore.Entities.Identity")
                        .WithMany("Roles")
                        .HasForeignKey("IdentityId");
                });
#pragma warning restore 612, 618
        }
    }
}
